import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { NextAuthProvider } from "./components/Providers";

const poppins = Poppins({
  weight: ["500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        {/* ทำให้ components สามารถเข้าถึงข้อมูล session authentication
         ผ่าน context ของ NextAuth ได้ */}
        <NextAuthProvider>{children}</NextAuthProvider>
      </body>
    </html>
  );
}
